<?php
echo '<!DOCTYPE html>';
echo '';
echo '<html>';
echo '';
echo '<head>';
echo '';
echo '<title>Shopping Cart</title>';
echo '';
echo '<link rel="stylesheet" type="text/css" href="cart.css">';
echo '';
echo '<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '';
echo '';
echo '<div class="container">';
echo '';
echo '<h1>Welcome to our Medicine shop</h1>';
echo '';
echo '<div class="cart">';
echo '';
echo '<div class="products">';
echo '';
echo '<div class="product">';
echo '';
echo '<img src="napa.jpg">';
echo '';
echo '<div class="product-info">';
echo '';
echo '<h3 class="product-name">NAPA EXTEND</h3>';
echo '';
echo '<h4 class="product-price">Tk 500</h4>';
echo '';
echo '<h4 class="product-offer">10% off</h4>';
echo '';
echo '<p class="product-quantity">Qnt: <input value="1" name="">';
echo '';
echo '<p class="product-remove">';
echo '';
echo '<i class="fa fa-trash" aria-hidden="true"></i>';
echo '';
echo '<span class="remove">Remove</span>';
echo '';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="product">';
echo '';
echo '<img src="histacin.jpg">';
echo '';
echo '<div class="product-info">';
echo '';
echo '<h3 class="product-name">HISTACIN</h3>';
echo '';
echo '<h4 class="product-price">TK 2,00</h4>';
echo '';
echo '<h4 class="product-offer">40% off</h4>';
echo '';
echo '<p class="product-quantity">Qnt: <input value="1" name="">';
echo '';
echo '<p class="product-remove">';
echo '';
echo '<i class="fa fa-trash" aria-hidden="true"></i>';
echo '';
echo '<span class="remove">Remove</span>';
echo '';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="cart-total">';
echo '';
echo '<p>';
echo '';
echo '<span>Total Price</span>';
echo '';
echo '<span>Tk 3,000</span>';
echo '';
echo '</p>';
echo '';
echo '<p>';
echo '';
echo '<span>Number of Items</span>';
echo '';
echo '<span>2</span>';
echo '';
echo '</p>';
echo '';
echo '<p>';
echo '';
echo '<span>You Save</span>';
echo '';
echo '<span>Tk 1,000</span>';
echo '';
echo '</p>';
echo '';
echo '<a href="#">Proceed to Checkout</a>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '</body>';
echo '';
echo '';
echo '</html>';
echo '';
?>